# Generated by Django 6.0.2 on 2026-03-02 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('customers', '0002_alter_customer_options'),
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='batchstock',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='batchbooking',
            name='batch_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='batch.batchstock'),
        ),
        migrations.AlterField(
            model_name='batchbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_bookings', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='batchbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batchstock',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'batch'}, on_delete=django.db.models.deletion.CASCADE, related_name='batch_stocks', to='products.product'),
        ),
    ]
