# Generated by Django 6.0.2 on 2026-03-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batchbooking_options_alter_batchstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchbooking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('wamd', 'WAMD')], max_length=10),
        ),
    ]
