# Generated by Django 6.0.2 on 2026-03-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_batchbooking_payment_method'),
        ('products', '0006_product_image_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchbooking',
            name='pieces_used',
            field=models.PositiveIntegerField(default=0, help_text='Snapshot: quantity × variant.pieces at booking time.'),
        ),
        migrations.AddField(
            model_name='batchbooking',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Which box size was ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='batchstock',
            name='booked_pieces',
            field=models.PositiveIntegerField(default=0, help_text='Pieces committed across all active bookings. Updated atomically.'),
        ),
        migrations.AddField(
            model_name='batchstock',
            name='collected_pieces',
            field=models.PositiveIntegerField(default=0, help_text='Pieces physically collected. Updated when booking status → collected.'),
        ),
        migrations.AddField(
            model_name='batchstock',
            name='total_pieces',
            field=models.PositiveIntegerField(default=0, help_text='Total individual pieces baked for this batch (e.g. 240 brownies)'),
        ),
        migrations.AlterField(
            model_name='batchstock',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BatchVariantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Owner toggle — set False to hide this box size from /shop for this batch')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=3, help_text="Override the variant's default price for this batch only. Null = use variant.price.", max_digits=8, null=True)),
                ('batch_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_configs', to='batch.batchstock')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_configs', to='products.productvariant')),
            ],
            options={
                'unique_together': {('batch_stock', 'variant')},
            },
        ),
    ]
