# Generated by Django 6.0.2 on 2026-03-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('custom', 'Custom'), ('batch', 'Batch')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, to='products.flavor'),
        ),
    ]
