# Generated by Django 6.0.2 on 2026-03-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flavor_remove_product_flavor_alter_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
