# Generated by Django 6.0.2 on 2026-03-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product display image shown in the shop and admin', null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField(help_text='Number of pieces in this box size, e.g. 3, 6, 12')),
                ('label', models.CharField(help_text="Display label shown to customers, e.g. '12 pcs box'", max_length=50)),
                ('price', models.DecimalField(decimal_places=3, help_text='Price for this box size in KD', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Global toggle — if False, this variant is hidden from all batches and the shop')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in the shop, lowest value shown first')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'pieces'],
                'unique_together': {('product', 'pieces')},
            },
        ),
    ]
