# Generated by Django 6.0.2 on 2026-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global toggle — if False, hidden from all batches and the shop'),
        ),
    ]
